<?php

namespace Database\Seeders;

use App\Enums\ProductType;
use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $supplierIdsByCode = Supplier::query()->pluck('id', 'code');

        $products = [
            [
                'supplier_code' => 'PROV-LAB-001',
                'sku' => 'MED-PARA-500-001',
                'barcode' => '7701234500011',
                'name' => 'Paracetamol 500 mg Tabletas x 100',
                'description' => 'Analgesico y antipiretico de alta rotacion.',
                'product_type' => ProductType::Medication,
                'brand' => 'Andino Pharma',
                'presentation' => 'Caja x 100 tabletas',
                'unit_of_measure' => 'box',
                'unit_content' => 100,
                'net_content_label' => '100 tabletas',
                'sale_price' => 18500,
                'cost_price' => 12900,
                'active_ingredient' => ['Paracetamol'],
                'concentration' => '500 mg',
                'presentation_type' => 'Tableta/Comprimido',
                'requires_prescription' => false,
                'is_controlled_substance' => false,
                'health_registration_number' => 'INVIMA-2026M-001001',
                'ingredients' => null,
                'allergens' => null,
                'nutritional_information' => null,
                'manufacturer' => 'Laboratorios Andinos S.A.S.',
                'model' => null,
                'warranty_months' => null,
                'medical_device_class' => null,
                'requires_calibration' => false,
                'storage_conditions' => 'Conservar por debajo de 30 C en lugar seco.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-LAB-001',
                'sku' => 'MED-IBUP-400-002',
                'barcode' => '7701234500012',
                'name' => 'Ibuprofeno 400 mg Capsulas x 30',
                'description' => 'Antiinflamatorio no esteroideo para dolor moderado.',
                'product_type' => ProductType::Medication,
                'brand' => 'Andino Pharma',
                'presentation' => 'Caja x 30 capsulas',
                'unit_of_measure' => 'box',
                'unit_content' => 30,
                'net_content_label' => '30 capsulas',
                'sale_price' => 21900,
                'cost_price' => 15400,
                'active_ingredient' => ['Ibuprofeno'],
                'concentration' => '400 mg',
                'presentation_type' => 'Capsula dura',
                'requires_prescription' => false,
                'is_controlled_substance' => false,
                'health_registration_number' => 'INVIMA-2026M-001002',
                'ingredients' => null,
                'allergens' => null,
                'nutritional_information' => null,
                'manufacturer' => 'Laboratorios Andinos S.A.S.',
                'model' => null,
                'warranty_months' => null,
                'medical_device_class' => null,
                'requires_calibration' => false,
                'storage_conditions' => 'Proteger de la luz directa y humedad.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-LAB-001',
                'sku' => 'MED-AMOX-875-003',
                'barcode' => '7701234500013',
                'name' => 'Amoxicilina 875 mg + Ac. Clavulanico x 14',
                'description' => 'Antibiotico de amplio espectro para infecciones respiratorias.',
                'product_type' => ProductType::Medication,
                'brand' => 'Andino Pharma',
                'presentation' => 'Caja x 14 tabletas recubiertas',
                'unit_of_measure' => 'box',
                'unit_content' => 14,
                'net_content_label' => '14 tabletas',
                'sale_price' => 46800,
                'cost_price' => 33750,
                'active_ingredient' => ['Amoxicilina/Clavulanico'],
                'concentration' => '875 mg / 125 mg',
                'presentation_type' => 'Tableta/Comprimido',
                'requires_prescription' => true,
                'is_controlled_substance' => false,
                'health_registration_number' => 'INVIMA-2026M-001003',
                'ingredients' => null,
                'allergens' => null,
                'nutritional_information' => null,
                'manufacturer' => 'Laboratorios Andinos S.A.S.',
                'model' => null,
                'warranty_months' => null,
                'medical_device_class' => null,
                'requires_calibration' => false,
                'storage_conditions' => 'Almacenar entre 15 C y 30 C.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-DERM-002',
                'sku' => 'PER-LOC-HIDRA-004',
                'barcode' => '7701234500014',
                'name' => 'Locion Hidratante Dermiplus 400 ml',
                'description' => 'Cuidado diario para piel sensible con pH balanceado.',
                'product_type' => ProductType::Perfumery,
                'brand' => 'DermiPlus',
                'presentation' => 'Frasco dosificador 400 ml',
                'unit_of_measure' => 'unit',
                'unit_content' => 400,
                'net_content_label' => '400 ml',
                'sale_price' => 32500,
                'cost_price' => 21800,
                'active_ingredient' => null,
                'concentration' => null,
                'presentation_type' => 'Locion',
                'requires_prescription' => false,
                'is_controlled_substance' => false,
                'health_registration_number' => null,
                'ingredients' => 'Agua, glicerina, pantenol, emolientes.',
                'allergens' => 'Sin fragancia',
                'nutritional_information' => null,
                'manufacturer' => 'Dermocosmetica Integral S.A.',
                'model' => null,
                'warranty_months' => null,
                'medical_device_class' => null,
                'requires_calibration' => false,
                'storage_conditions' => 'Mantener tapado y lejos de calor extremo.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-DERM-002',
                'sku' => 'HIG-GEL-ANTI-005',
                'barcode' => '7701234500015',
                'name' => 'Gel Antibacterial 70% 250 ml',
                'description' => 'Gel de higiene de manos con secado rapido.',
                'product_type' => ProductType::PersonalHygiene,
                'brand' => 'DermiPlus',
                'presentation' => 'Frasco 250 ml',
                'unit_of_measure' => 'unit',
                'unit_content' => 250,
                'net_content_label' => '250 ml',
                'sale_price' => 12900,
                'cost_price' => 8200,
                'active_ingredient' => null,
                'concentration' => null,
                'presentation_type' => 'Gel',
                'requires_prescription' => false,
                'is_controlled_substance' => false,
                'health_registration_number' => null,
                'ingredients' => 'Alcohol etilico 70%, glicerina, carbomero.',
                'allergens' => null,
                'nutritional_information' => null,
                'manufacturer' => 'Dermocosmetica Integral S.A.',
                'model' => null,
                'warranty_months' => null,
                'medical_device_class' => null,
                'requires_calibration' => false,
                'storage_conditions' => 'Inflamable. Mantener lejos de fuentes de ignicion.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-NUT-003',
                'sku' => 'ALI-ENTERAL-006',
                'barcode' => '7701234500016',
                'name' => 'Formula Enteral Hipercalorica 1 L',
                'description' => 'Formula para soporte nutricional en pacientes con alto requerimiento.',
                'product_type' => ProductType::Food,
                'brand' => 'NutriVida',
                'presentation' => 'Botella esteril 1 litro',
                'unit_of_measure' => 'unit',
                'unit_content' => 1,
                'net_content_label' => '1 L',
                'sale_price' => 45800,
                'cost_price' => 33600,
                'active_ingredient' => null,
                'concentration' => null,
                'presentation_type' => 'Emulsion',
                'requires_prescription' => false,
                'is_controlled_substance' => false,
                'health_registration_number' => null,
                'ingredients' => 'Proteina aislada, trigliceridos MCT, vitaminas y minerales.',
                'allergens' => 'Contiene proteina de leche y soya.',
                'nutritional_information' => '1.5 kcal/ml. Proteina 63 g por litro.',
                'manufacturer' => 'NutriVida Distribuciones S.A.S.',
                'model' => null,
                'warranty_months' => null,
                'medical_device_class' => null,
                'requires_calibration' => false,
                'storage_conditions' => 'Conservar entre 15 C y 25 C. No congelar.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-NUT-003',
                'sku' => 'ALI-SUPL-ADUL-007',
                'barcode' => '7701234500017',
                'name' => 'Suplemento Proteico Adulto Vainilla 400 g',
                'description' => 'Suplemento en polvo para soporte nutricional oral.',
                'product_type' => ProductType::Food,
                'brand' => 'NutriVida',
                'presentation' => 'Lata 400 g',
                'unit_of_measure' => 'unit',
                'unit_content' => 400,
                'net_content_label' => '400 g',
                'sale_price' => 39200,
                'cost_price' => 28100,
                'active_ingredient' => null,
                'concentration' => null,
                'presentation_type' => 'Polvo para reconstituir',
                'requires_prescription' => false,
                'is_controlled_substance' => false,
                'health_registration_number' => null,
                'ingredients' => 'Proteina concentrada, vitaminas, minerales y fibra soluble.',
                'allergens' => 'Contiene leche.',
                'nutritional_information' => '25 g de proteina por porcion.',
                'manufacturer' => 'NutriVida Distribuciones S.A.S.',
                'model' => null,
                'warranty_months' => null,
                'medical_device_class' => null,
                'requires_calibration' => false,
                'storage_conditions' => 'Mantener bien cerrado en lugar fresco y seco.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-MED-004',
                'sku' => 'EQU-TENS-08',
                'barcode' => '7701234500018',
                'name' => 'Tensiometro Digital de Brazo TM-800',
                'description' => 'Dispositivo automatico para control de presion arterial.',
                'product_type' => ProductType::MedicalEquipment,
                'brand' => 'TecnoMed',
                'presentation' => 'Kit con brazalete universal y estuche',
                'unit_of_measure' => 'unit',
                'unit_content' => 1,
                'net_content_label' => 'Unidad',
                'sale_price' => 149900,
                'cost_price' => 112500,
                'active_ingredient' => null,
                'concentration' => null,
                'presentation_type' => null,
                'requires_prescription' => false,
                'is_controlled_substance' => false,
                'health_registration_number' => null,
                'ingredients' => null,
                'allergens' => null,
                'nutritional_information' => null,
                'manufacturer' => 'TecnoMed Equipos Clinicos S.A.S.',
                'model' => 'TM-800',
                'warranty_months' => 24,
                'medical_device_class' => 'IIa',
                'requires_calibration' => true,
                'storage_conditions' => 'Guardar en estuche. Evitar golpes y humedad.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-MED-004',
                'sku' => 'EQU-GLUCO-09',
                'barcode' => '7701234500019',
                'name' => 'Glucometro Portatil GM-220',
                'description' => 'Equipo para medicion de glucosa capilar en segundos.',
                'product_type' => ProductType::MedicalEquipment,
                'brand' => 'TecnoMed',
                'presentation' => 'Estuche con medidor, lancetas y tiras iniciales',
                'unit_of_measure' => 'unit',
                'unit_content' => 1,
                'net_content_label' => 'Unidad',
                'sale_price' => 99500,
                'cost_price' => 73100,
                'active_ingredient' => null,
                'concentration' => null,
                'presentation_type' => null,
                'requires_prescription' => false,
                'is_controlled_substance' => false,
                'health_registration_number' => null,
                'ingredients' => null,
                'allergens' => null,
                'nutritional_information' => null,
                'manufacturer' => 'TecnoMed Equipos Clinicos S.A.S.',
                'model' => 'GM-220',
                'warranty_months' => 18,
                'medical_device_class' => 'IIa',
                'requires_calibration' => true,
                'storage_conditions' => 'Temperatura ambiente. No exponer a luz solar directa.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
            [
                'supplier_code' => 'PROV-GEN-005',
                'sku' => 'MED-LOS-50-010',
                'barcode' => '7701234500020',
                'name' => 'Losartan 50 mg Tabletas x 30',
                'description' => 'Antihipertensivo de uso cronico.',
                'product_type' => ProductType::Medication,
                'brand' => 'GenCaribe',
                'presentation' => 'Caja x 30 tabletas',
                'unit_of_measure' => 'box',
                'unit_content' => 30,
                'net_content_label' => '30 tabletas',
                'sale_price' => 17400,
                'cost_price' => 11850,
                'active_ingredient' => ['Losartan'],
                'concentration' => '50 mg',
                'presentation_type' => 'Tableta/Comprimido',
                'requires_prescription' => true,
                'is_controlled_substance' => false,
                'health_registration_number' => 'INVIMA-2026M-001010',
                'ingredients' => null,
                'allergens' => null,
                'nutritional_information' => null,
                'manufacturer' => 'Distribuciones Genericas del Caribe S.A.S.',
                'model' => null,
                'warranty_months' => null,
                'medical_device_class' => null,
                'requires_calibration' => false,
                'storage_conditions' => 'Conservar a temperatura no mayor de 30 C.',
                'is_active' => true,
                'created_by' => 'ProductSeeder',
                'updated_by' => 'ProductSeeder',
            ],
        ];

        foreach ($products as $product) {
            $supplierCode = $product['supplier_code'];
            unset($product['supplier_code']);
            $product['discount_percent'] = $product['discount_percent'] ?? 0;

            $isMedication = ($product['product_type'] ?? null) === ProductType::Medication;
            unset($product['product_type']);

            $product['slug'] = Str::slug($product['sku']);

            $sale = (float) $product['sale_price'];
            $cost = isset($product['cost_price']) && $product['cost_price'] !== null && $product['cost_price'] !== ''
                ? (float) $product['cost_price']
                : 0.0;
            $profitPercent = $cost > 0.00001
                ? round((($sale / $cost) - 1) * 100, 4)
                : 0.0;
            $slug = 'cat-'.Str::slug($product['sku']);

            $category = ProductCategory::query()->updateOrCreate(
                ['slug' => $slug],
                [
                    'name' => 'Cat. '.$product['name'],
                    'description' => null,
                    'image' => null,
                    'is_active' => true,
                    'is_medication' => $isMedication,
                    'profit_percentage' => $profitPercent,
                    'created_by' => 'ProductSeeder',
                    'updated_by' => 'ProductSeeder',
                ],
            );
            $product['product_category_id'] = $category->id;

            $supplierId = $supplierIdsByCode->get($supplierCode);

            if ($supplierId === null) {
                continue;
            }

            $product['supplier_id'] = (int) $supplierId;

            Product::query()->updateOrCreate(
                ['sku' => $product['sku']],
                $product,
            );
        }
    }
}
