<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>1.2.1</Version>
    <Company>Farmadoc</Company>
    <Product>Farmadoc Fiscal Agent</Product>
  </PropertyGroup>
</Project>
